--- ./mic_cases/base/test.ks	2011-02-25 09:21:41.778621925 +0800
+++ /home/zhou/Code/minimal.ks	2011-02-25 15:22:26.878620886 +0800
@@ -1,66 +1,322 @@
-#
-# Do not Edit! Generated by:
-# kickstarter.py
-# 
+# kickstart file for MeeGo minimal compliance image
+# Usage: $ sudo mic-image-creator --run-mode=0 --cache=mycachedir --format=fs --config=<meego-minimal-compliance-xxxx.ks> --package=tar.bz2 --include-source
 
 lang en_US.UTF-8
 keyboard us
-timezone --utc America/New_York
+timezone --utc America/Los_Angeles
 auth --useshadow --enablemd5
-part / --size 3000 --ondisk sda --fstype=ext3
-rootpw meego 
-xconfig --startxonboot
+part / --size 1600 --ondisk sda --fstype=ext3
+rootpw meego
 bootloader --timeout=0 --append="quiet"
-desktop --autologinuser=meego 
-user --name meego  --groups audio,video --password meego 
+user --name meego  --groups audio,video --password meego
 
+repo   --name=non-oss --baseurl=http://linux-ftp.jf.intel.com/pub/mirrors/MeeGo-other/trunk-daily/builds/trunk/1.1.90.3.20110214.2/non-oss/repos/ia32/packages/ --save  --debuginfo --source --gpgkey=file:///eetc/pki/rpm-gpg/RPM-GPG-KEY-meego 
 repo   --name=oss --baseurl=http://linux-ftp.jf.intel.com/pub/mirrors/MeeGo-other/trunk-daily/builds/trunk/1.1.90.3.20110214.2/oss/repos/ia32/packages/ --save  --debuginfo --source --gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-meego 
 
-%packages
-@MeeGo Core
-@MeeGo Netbook Desktop
-@X for Netbooks
-@MeeGo Compliance
-@MeeGo X Window System
-@Virtual Machine Support
-@Games
-@Printing
-@Base Double Byte IME Support
-@MeeGo Base Development
-
-kernel
-chromium 
+%packages --ignoremissing
+libacl
+alsa-lib
+libattr
+basesystem
+bash
+bluez
+bluez-libs
+buteo-mtp
+buteo-syncfw
+buteo-syncml
+buteo-sync-plugins
+bzip2-libs
+cairo
+chkconfig
+connman
+ConsoleKit
+ConsoleKit-libs
+contextkit
+coreutils
+cryptsetup-luks
+curl
+libcurl
+cyrus-sasl-lib
+db4
+db4-utils
+dbus
+dbus-libs
+dbus-x11
+dbus-glib
+desktop-file-utils
+device-mapper-libs
+dsme
+libiphb
+e2fsprogs
+e2fsprogs-libs
+libcom_err
+libss
+eggdbus
+elfutils-libelf
+exempi
+expat
+farsight2
+file-libs
+filesystem
+flac
+fontconfig
+freetype
+gamin
+libgcc
+libstdc++
+GConf-dbus
+gdbm
+giflib
+glib2
+glibc
+glibc-common
+gmime
+gnupg2
+gnutls
+grep
+gssdp
+gst-plugins-base
+gst-plugins-good
+gstreamer
+gtk2
+gupnp
+gupnp-igd
+hwdata
+libicu
+jasper
+jasper-libs
+kcalcore
+kernel>=2.6.35
+keyutils-libs
+krb5-libs
+lcms
+lcms-libs
+libaccounts-glib
+libaccounts-qt
+libarchive
+libatasmart
+libcap
+libcreds2
+libdaemon
+libdres
+ohm-plugin-resolver
+libdrm
+libdsme
+libexif
+libffi
+libfontenc
+libgcrypt
+libgdbus
+libgee
+libgnome-keyring
+libgpg-error
+libgsf
+libical
+libICE
+libidn
+libiodata
+libjpeg
+libmng
+libnice
+libnl
+libogg
+libpng
+libprolog
+libqmlog
+libqttracker
+libresource
+libresource-client
+satsolver-tools
+libsignon
+libsignon-passwordplugin
+libsignon-saslplugin
+libSM
+libsndfile
+libsoup
+libtasn1
+libtelepathy
+libthai
+libtheora
+libtiff
+libtool-ltdl
+libtrace
+libusb
+libuser
+libvisual
+libvorbis
+libX11
+libXau
+libXaw
+libxcb
+libXcomposite
+libXcursor
+libXdamage
+libXext
+libXfixes
+libXfont
+libXft
+libXi
+libXinerama
+libxkbfile
+libxml2
+libXmu
+libXpm
+libXrandr
+libXrender
+libXt
+libXtst
+libXv
+libXxf86vm
+libzypp
+/usr/lib/libGL.so.1
+/usr/lib/libEGL.so.1
+mesa-libGLUT
+mesa-libOSMesa
+mingetty
+ncurses
+ncurses-base
+ncurses-libs
+nspr
+nss
+nss-softokn-freebl
+nss-sysinit
+o3read
+obexd
+ofono
+ohm
+ohm-config
+ohm-plugin-core
+ohm-plugins-misc
+openjpeg-libs
+openobex
+openssl
+orc
+PackageKit
+PackageKit-glib
+PackageKit-gtk-module
+PackageKit-qt
+PackageKit-zypp
+pam
+pango
+passwd
+pciutils
+pcre
+libphonon4
+pixman
+pm-utils
+polkit
+poppler
+poppler-utils
+popt
+pulseaudio
+python
+python-libs
+qjson
+libqtcore4
+libqtdbus4
+libqtdeclarative4
+libqtdeclarative4-folderlistmodel
+libqtdeclarative4-gestures
+libqtdeclarative4-particles
+libqtdesigner4
+libqtgui4
+libqtnetwork4
+libqtopengl4
+libqtscript4
+libqtsql4
+libqtsql4-sqlite
+libqtsvg4
+libqttest4
+libqtxml4
+libqtxmlpatterns4
+qtcontacts-tracker
+libdeclarative-contacts
+libdeclarative-multimedia
+libdeclarative-publishsubscribe
+libdeclarative-sensors
+libdeclarative-serviceframework
+libqtcontacts1
+libqtlocation1
+libqtmessaging1
+libqtmultimediakit1
+libqtpublishsubscribe1
+libqtsensors1
+libqtserviceframework1
+libqtsysteminfo1
+libqtversit1
+qt-mobility
+servicefw
+libqtwebkit4
+libqtwebkit-qmlwebkitplugin
+readline
+rpm
+rpm-libs
+rtkit
+sed
+sensorfw
+setup
+sg3_utils-libs
+shadow-utils
+shared-mime-info
+sofia-sip
+sofia-sip-glib
+speex
+sqlite
+swi-prolog
+swi-prolog-library
+swi-prolog-library-core
+sysvinit
+sysvinit-tools
+taglib
+telepathy-farsight
+telepathy-gabble
+telepathy-glib
+telepathy-mission-control
+telepathy-qt4
+telepathy-qt4-farsight
+telepathy-ring
+telepathy-sofiasip
+telepathy-stream-engine
+timed
+tinycdb
+totem-pl-parser
+tracker
+tzdata
+libgudev1
+libudev
+udev
+udisks
+upower
+usermode
+libblkid
+libuuid
+util-linux-ng
+wpa_supplicant
+xcb-util
+xorg-x11-font-utils
+xorg-x11-server
+xorg-x11-server-common
+xorg-x11-utils
+xorg-x11-utils-xdpyinfo
+xorg-x11-utils-xdriinfo
+xorg-x11-utils-xev
+xorg-x11-utils-xfd
+xorg-x11-utils-xfontsel
+xorg-x11-utils-xlsatoms
+xorg-x11-utils-xlsclients
+xorg-x11-utils-xlsfonts
+xorg-x11-utils-xprop
+xorg-x11-utils-xrandr
+xorg-x11-utils-xvinfo
+xorg-x11-utils-xwininfo
+xorg-x11-xauth
+xorg-x11-xkb-utils
+xz-libs
+zlib
 %end
 
 %post
-
-# save a little bit of space at least...
-rm -f /boot/initrd*
-
 # make sure there aren't core files lying around
 rm -f /core*
-
-
-
-# Prelink can reduce boot time
-if [ -x /usr/sbin/prelink ]; then
-    /usr/sbin/prelink -aRqm
-fi
-
-
-# work around for poor key import UI in PackageKit
-rm -f /var/lib/rpm/__db*
 rpm --rebuilddb
-
-if [ -f /etc/pki/rpm-gpg/RPM-GPG-KEY-meego ]; then
-    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-meego
-fi
-
-
-%end
-
-%post --nochroot
-if [ -n "$IMG_NAME" ]; then
-    echo "BUILD: $IMG_NAME" >> $INSTALL_ROOT/etc/meego-release
-fi
 %end
