--- ./mic_cases/base/test.ks	2011-02-25 09:21:41.778621925 +0800
+++ /home/zhou/Code/min_nb.ks	2011-02-23 12:19:12.453405953 +0800
@@ -1,4 +1,4 @@
-#
+# 
 # Do not Edit! Generated by:
 # kickstarter.py
 # 
@@ -15,25 +15,17 @@ desktop --autologinuser=meego
 user --name meego  --groups audio,video --password meego 
 
 repo   --name=oss --baseurl=http://linux-ftp.jf.intel.com/pub/mirrors/MeeGo-other/trunk-daily/builds/trunk/1.1.90.3.20110214.2/oss/repos/ia32/packages/ --save  --debuginfo --source --gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-meego 
+repo   --name=oss-source --baseurl=http://linux-ftp.jf.intel.com/pub/mirrors/MeeGo-other/trunk-daily/builds/trunk/1.1.90.3.20110214.2/oss/repos/source/ --source
 
-%packages
-@MeeGo Core
-@MeeGo Netbook Desktop
-@X for Netbooks
-@MeeGo Compliance
-@MeeGo X Window System
-@Virtual Machine Support
-@Games
-@Printing
-@Base Double Byte IME Support
-@MeeGo Base Development
-
-kernel
-chromium 
+%packages --ignoremissing
+libacl
+alsa-lib
+libattr
+basesystem
+bash
 %end
 
 %post
-
 # save a little bit of space at least...
 rm -f /boot/initrd*
 
