# -*-mic2-options-*- -f livecd -*-mic2-options-*-

# 
# Do not Edit! Generated by:
# kickstarter.py
# 

lang en_US.UTF-8
keyboard us
timezone --utc America/Los_Angeles
part / --size 2200 --ondisk sda --fstype=ext3
rootpw meego 
xconfig --startxonboot
bootloader --timeout=0 --append="quiet"
desktop --autologinuser=meego  --defaultdesktop=X-IVI --session="/usr/bin/startivi"
user --name meego  --groups audio,video --password meego 

repo --name=oss --baseurl=http://linux-ftp.jf.intel.com/pub/mirrors/MeeGo/builds/1.2.80/1.2.80.0.20110503.2/repos/oss/ia32/packages/ --save --debuginfo --source --gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-meego
repo --name=non-oss --baseurl=http://linux-ftp.jf.intel.com/pub/mirrors/MeeGo/builds/1.2.80/1.2.80.0.20110503.2/repos/non-oss/ia32/packages/ --save --debuginfo --source --gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-meego

%packages --ignoremissing

@MeeGo Core
@MeeGo Compliance
@IVI Desktop
@MeeGo X Window System
@MeeGo IVI Applications
@MeeGo Base Development
@X for IVI
@Chinese Support
@Japanese Support
@Korean Support

kernel-adaptation-intel-automotive

meego-ux-daemon
meegotouch-compositor
-dsme
-ngfd
-mce
-qmsystem
%end

%post
# save a little bit of space at least...
rm -f /boot/initrd*

# Prelink can reduce boot time
if [ -x /usr/sbin/prelink ]; then
    /usr/sbin/prelink -aRqm
fi

rm -f /var/lib/rpm/__db*
rpm --rebuilddb

# Get rid of /etc/xdg/autostart/applauncherd.desktop line that causes IVI duicontrolpanel issues
# until fixed upstream. BMC#13570
sed -ri '/OnlyShowIn=X-MEEGO-HS;/d' /etc/xdg/autostart/applauncherd.desktop


%end

%post --nochroot
if [ -n "$IMG_NAME" ]; then
    echo "BUILD: $IMG_NAME" >> $INSTALL_ROOT/etc/meego-release
fi


%end
