# -*-mic2-options-*- -f livecd -*-mic2-options-*-

# 
# Do not Edit! Generated by:
# kickstarter.py
# 

lang en_US.UTF-8
keyboard us
timezone --utc America/Los_Angeles
part / --size 3000 --ondisk sda --fstype=ext3
rootpw meego 
xconfig --startxonboot
bootloader --timeout=0 --append="quiet"
desktop --autologinuser=meego  
user --name meego  --groups audio,video --password meego 

repo --name=1.2-oss --baseurl=http://repo.meego.com/MeeGo/releases/1.2.0/repos/oss/ia32/packages/ --save --debuginfo --source --gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-meego
repo --name=1.2-non-oss --baseurl=http://repo.meego.com/MeeGo/releases/1.2.0/repos/non-oss/ia32/packages/ --save --debuginfo --source --gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-meego
repo --name=1.2-oss-source --baseurl=http://repo.meego.com/MeeGo/releases/1.2.0/repos/oss/source/ --save --source
repo --name=1.2-non-oss-source --baseurl=http://repo.meego.com/MeeGo/releases/1.2.0/repos/non-oss/source --save --source

%packages

@MeeGo Base Development
@Base Double Byte IME Support
@MeeGo Compliance
@MeeGo Core
@MeeGo X Window System
@X for Netbooks
@MeeGo Netbook
@MeeGo Netbook Desktop
@Printing
@Games

kernel-adaptation-pinetrail

%end

%post
# save a little bit of space at least...
rm -f /boot/initrd*

# Prelink can reduce boot time
if [ -x /usr/sbin/prelink ]; then
    /usr/sbin/prelink -aRqm
fi

rm -f /var/lib/rpm/__db*
rpm --rebuilddb


%end

%post --nochroot
if [ -n "$IMG_NAME" ]; then
    echo "BUILD: $IMG_NAME" >> $INSTALL_ROOT/etc/meego-release
fi


%end
