#
# Do not Edit! Generated by:
# kickstarter.py
# 

lang en_US.UTF-8
keyboard us
timezone --utc America/New_York
auth --useshadow --enablemd5
part / --size 3000 --ondisk sda --fstype=ext3
rootpw meego 
xconfig --startxonboot
bootloader --timeout=0 --append="quiet"
desktop --autologinuser=meego 
user --name meego  --groups audio,video --password meego 

repo   --name=oss --baseurl=http://linux-ftp.jf.intel.com/pub/mirrors/MeeGo-other/trunk-daily/builds/trunk/1.1.90.3.20110214.2/oss/repos/ia32/packages/ --save  --debuginfo --source --gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-meego 

%packages
@MeeGo Core
@MeeGo Netbook Desktop
@X for Netbooks
@MeeGo Compliance
@MeeGo X Window System
@Virtual Machine Support
@Games
@Printing
@Base Double Byte IME Support
@MeeGo Base Development

kernel
chromium 
%end

%post

# save a little bit of space at least...
rm -f /boot/initrd*

# make sure there aren't core files lying around
rm -f /core*



# Prelink can reduce boot time
if [ -x /usr/sbin/prelink ]; then
    /usr/sbin/prelink -aRqm
fi


# work around for poor key import UI in PackageKit
rm -f /var/lib/rpm/__db*
rpm --rebuilddb

if [ -f /etc/pki/rpm-gpg/RPM-GPG-KEY-meego ]; then
    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-meego
fi


%end

%post --nochroot
if [ -n "$IMG_NAME" ]; then
    echo "BUILD: $IMG_NAME" >> $INSTALL_ROOT/etc/meego-release
fi
%end
