--- ./mic_cases/base/test.ks	2011-08-23 09:44:14.192145003 +0800
+++ meego-handset-armv7l-n900-1.1.ks	2011-08-23 10:31:43.047093908 +0800
@@ -1,60 +1,93 @@
-# 
-# Do not Edit! Generated by:
-# kickstarter.py
-# 
-
 lang en_US.UTF-8
 keyboard us
 timezone --utc America/Los_Angeles
-part / --size 3000 --ondisk sda --fstype=ext3
-rootpw meego 
+#auth --useshadow --enablemd5
+#part / --size=1600  --ondisk mmcblk0p --fstype=btrfs
+part / --size=1750  --ondisk mmcblk0p --fstype=ext3
+
+# Add swap partition. It is a bit bad practise to have the swap on the same 
+# device as root partition, but currently we do not want to do changes to the
+# N900 internal memories (emmc or nand).
+part swap --size=256 --ondisk mmcblk0p --fstype=swap
+
+rootpw meego
 xconfig --startxonboot
-bootloader --timeout=0 --append="quiet"
-desktop --autologinuser=meego  
-user --name meego  --groups audio,video --password meego 
+desktop --autologinuser=meego  --defaultdesktop=DUI --session=/usr/bin/mcompositor
+user --name meego  --groups audio,video --password meego
 
-repo --name=1.2-oss --baseurl=http://download.meego.com/snapshots/1.2.0.90.12.20110808.80/repos/oss/ia32/packages/ --save --debuginfo --source --gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-meego
-repo --name=1.2-non-oss --baseurl=http://download.meego.com/snapshots/1.2.0.90.12.20110808.80/repos/non-oss/ia32/packages/ --save --debuginfo --source --gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-meego
+repo --name=core     --baseurl=http://linux-ftp.intel.com/pub/mirrors/MeeGo/releases/1.1/core/repos/armv7l/packages/ --save --debuginfo --source --gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-meego01
+repo --name=handset  --baseurl=http://linux-ftp.intel.com/pub/mirrors/MeeGo/releases/1.1/handset/repos/armv7l/packages/ --save --debuginfo --source --gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-meego01
+repo --name=non-oss  --baseurl=http://linux-ftp.intel.com/pub/mirrors/MeeGo/releases/1.1/non-oss/repos/armv7l/packages/ --save --debuginfo --source --gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-meego01
 
 %packages
-
-@MeeGo Base Development
-@Base Double Byte IME Support
-@MeeGo Compliance
 @MeeGo Core
-@MeeGo X Window System
-@X for Netbooks
-@MeeGo Netbook
-@MeeGo Netbook Desktop
-@Printing
-@Games
-
-kernel-adaptation-pinetrail
-
-chromium
--adobe-release
--flash-plugin
+@MeeGo Base
+@Minimal MeeGo X Window System
+@MeeGo Compliance
+@Nokia N900 Support
+@MeeGo Handset Desktop
+@MeeGo Handset Applications
+@MeeGo Handset Applications Branding
+@Nokia N900 Proprietary Support
+@X for Handsets
+@MeeGo Handset Base Support
+
+# Some development tools
+openssh-server
+wget
+strace
+bootchart
+gdb
+gdb-gdbserver
+
+# Some extra tools/libs
+connman-test
+xorg-x11-utils-xev
+
+# http://bugs.meego.com/show_bug.cgi?id=5651
+-meegotouch-inputmethodbridges
+-meegotouch-inputmethodframework
+-meegotouch-inputmethodkeyboard
+-meegotouch-inputmethodengine
 %end
 
 %post
-# save a little bit of space at least...
-rm -f /boot/initrd*
+# Prelink not included because of following bug
+# http://bugs.meego.com/show_bug.cgi?id=5217
 
-# Prelink can reduce boot time
-if [ -x /usr/sbin/prelink ]; then
-    /usr/sbin/prelink -aRqm
-fi
+# make sure there aren't core files lying around
+rm -f /core*
+
+# open serial line console for embedded system
+echo "s0:235:respawn:/sbin/agetty -L 115200 ttyS2 vt100" >> /etc/inittab
 
+# work around for poor key import UI in PackageKit
 rm -f /var/lib/rpm/__db*
 rpm --rebuilddb
 
-
+# Set up sane defaults for mthemedaemon settings
+Config_Src=`gconftool-2 --get-default-source`
+gconftool-2 --direct --config-source $Config_Src \
+  -s -t string /meegotouch/theme/target N900
+
+# By default N900 has different value than Aava for showStatusBar
+sed -i 's!showStatusBar=false!showStatusBar=true!g' /etc/meegotouch/devices.conf
+
+# Normal bootchart is only 30 long so we use this to get longer bootchart during startup when needed.
+cat > /sbin/bootchartd-long << EOF
+#!/bin/sh
+exec /sbin/bootchartd -n 4000
+EOF
+chmod +x /sbin/bootchartd-long
+
+# Temporary fix for BMC#8664 to get fennec startup time more reasonable.
+mkdir -p /home/meego/.mozilla/
+chown -R meego:meego /home/meego/.mozilla/
+echo "tmpfs /home/meego/.mozilla tmpfs     size=20m      0   0" >> /etc/fstab
 %end
 
 %post --nochroot
 if [ -n "$IMG_NAME" ]; then
     echo "BUILD: $IMG_NAME" >> $INSTALL_ROOT/etc/meego-release
 fi
-
-
 %end
