--- ./mic_cases/base/test.ks	2011-02-25 09:21:41.778621925 +0800
+++ /home/zhou/Code/handset.ks	2011-02-22 18:05:32.693146002 +0800
@@ -1,62 +1,80 @@
-#
+# 
 # Do not Edit! Generated by:
 # kickstarter.py
 # 
 
 lang en_US.UTF-8
 keyboard us
-timezone --utc America/New_York
+timezone --utc America/Los_Angeles
 auth --useshadow --enablemd5
-part / --size 3000 --ondisk sda --fstype=ext3
+part / --size 1700 --ondisk sda --fstype=ext3
 rootpw meego 
 xconfig --startxonboot
-bootloader --timeout=0 --append="quiet"
-desktop --autologinuser=meego 
+bootloader --timeout=2 --append="ro pci=noearly console=tty1 console=ttyS0 console=ttyMFD2 earlyprintk=mrst loglevel=8 s0ix_latency=160"
+desktop --autologinuser=meego  --defaultdesktop=DUI --session="/usr/bin/mcompositor"
 user --name meego  --groups audio,video --password meego 
 
-repo   --name=oss --baseurl=http://linux-ftp.jf.intel.com/pub/mirrors/MeeGo-other/trunk-daily/builds/trunk/1.1.90.3.20110214.2/oss/repos/ia32/packages/ --save  --debuginfo --source --gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-meego 
+repo   --name=oss     --baseurl=http://linux-ftp.jf.intel.com/pub/mirrors/MeeGo-other/trunk-daily/builds/trunk/1.1.90.3.20110214.2/oss/repos/ia32/packages/ --save --debuginfo --source --gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-meego
+repo   --name=non-oss  --baseurl=http://linux-ftp.jf.intel.com/pub/mirrors/MeeGo-other/trunk-daily/builds/trunk/1.1.90.3.20110214.2/non-oss/repos/ia32/packages/ --save --debuginfo --source --gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-meego
+repo   --name=oss-source  --baseurl=http://linux-ftp.jf.intel.com/pub/mirrors/MeeGo-other/trunk-daily/builds/trunk/1.1.90.3.20110214.2/oss/repos/source/ --source
+repo   --name=non-oss-source  --baseurl=http://linux-ftp.jf.intel.com/pub/mirrors/MeeGo-other/trunk-daily/builds/trunk/1.1.90.3.20110214.2/non-oss/repos/source/ --source
+
+%packages 
 
-%packages
 @MeeGo Core
-@MeeGo Netbook Desktop
-@X for Netbooks
+@Minimal MeeGo X Window System
+@X for Handsets 
 @MeeGo Compliance
-@MeeGo X Window System
-@Virtual Machine Support
-@Games
-@Printing
-@Base Double Byte IME Support
+@MeeGo Handset Desktop
+@MeeGo Handset Applications
+@Moorestown Support
 @MeeGo Base Development
 
-kernel
-chromium 
+kernel-adaptation-medfield
+#pulseaudio-modules-mfld
+
 %end
 
 %post
 
-# save a little bit of space at least...
-rm -f /boot/initrd*
+#Create Initrd if it does not exist and create symlinks for bzImage and initrd for kboot autoboot
+echo "ro pci=noearly console=tty1 console=ttyS0 console=ttyMFD2 earlyprintk=mrst loglevel=8 s0ix_latency=160" > /boot/kboot.cmdline
+
+echo "Checking for kernel......."
+Kernel_Name=`ls /boot | grep vmlinuz`
+if [ -f /boot/$Kernel_Name ]; then
+        Kernel_Ver=`echo $Kernel_Name | sed s/vmlinuz-//`
+        if [ -f /boot/initrd* ]; then
+                echo "Initrd exists" > /dev/null
+        else
+                /usr/libexec/mkmrstinitrd /boot/initrd-$Kernel_Ver.img $Kernel_Ver
+        fi
+        #Create Symlinks
+        cd /boot
+        ln -s $Kernel_Name bzImage
+        ln -s initrd-$Kernel_Ver.img initrd
+        ln -s kboot.cmdline cmdline
+else
+        echo "No Kernels were found"
+fi
 
 # make sure there aren't core files lying around
 rm -f /core*
 
-
-
 # Prelink can reduce boot time
 if [ -x /usr/sbin/prelink ]; then
     /usr/sbin/prelink -aRqm
 fi
 
+# open serial line console for embedded system
+echo "s0:235:respawn:/sbin/agetty -L 115200 ttyS0 vt100" >> /etc/inittab
+echo "s1:235:respawn:/sbin/agetty -L 115200 ttyMFD2 vt100" >> /etc/inittab
+echo "ttyMFD2" >> /etc/securetty
 
 # work around for poor key import UI in PackageKit
 rm -f /var/lib/rpm/__db*
 rpm --rebuilddb
 
-if [ -f /etc/pki/rpm-gpg/RPM-GPG-KEY-meego ]; then
-    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-meego
-fi
-
-
 %end
 
 %post --nochroot
