--- ./mic_cases/base/test.ks	2011-02-25 09:21:41.778621925 +0800
+++ ../tools/invalidrepo.ks	2011-02-21 17:04:40.663145997 +0800
@@ -1,4 +1,4 @@
-#
+# 
 # Do not Edit! Generated by:
 # kickstarter.py
 # 
@@ -7,47 +7,45 @@ lang en_US.UTF-8
 keyboard us
 timezone --utc America/New_York
 auth --useshadow --enablemd5
-part / --size 3000 --ondisk sda --fstype=ext3
+part / --size 2200 --ondisk sda --fstype=ext3
 rootpw meego 
 xconfig --startxonboot
 bootloader --timeout=0 --append="quiet"
-desktop --autologinuser=meego 
+desktop --autologinuser=meego  --defaultdesktop=X-IVI --session=/usr/bin/startivi
 user --name meego  --groups audio,video --password meego 
 
-repo   --name=oss --baseurl=http://linux-ftp.jf.intel.com/pub/mirrors/MeeGo-other/trunk-daily/builds/trunk/1.1.90.3.20110214.2/oss/repos/ia32/packages/ --save  --debuginfo --source --gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-meego 
-
-%packages
+repo --save=0 --debuginfo --source --name=core       --baseurl=http://xxx.com --gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-meego
+%packages 
 @MeeGo Core
-@MeeGo Netbook Desktop
-@X for Netbooks
 @MeeGo Compliance
+@X for IVI
+@IVI Desktop
 @MeeGo X Window System
-@Virtual Machine Support
-@Games
-@Printing
-@Base Double Byte IME Support
+@MeeGo IVI Applications
 @MeeGo Base Development
+@Development Tools
+
+kernel-adaptation-intel-automotive
+
+# forced for compliance...
+mesa-libEGL
 
-kernel
-chromium 
 %end
 
 %post
 
+
 # save a little bit of space at least...
 rm -f /boot/initrd*
 
 # make sure there aren't core files lying around
 rm -f /core*
 
-
-
 # Prelink can reduce boot time
 if [ -x /usr/sbin/prelink ]; then
     /usr/sbin/prelink -aRqm
 fi
 
-
 # work around for poor key import UI in PackageKit
 rm -f /var/lib/rpm/__db*
 rpm --rebuilddb
@@ -56,7 +54,6 @@ if [ -f /etc/pki/rpm-gpg/RPM-GPG-KEY-mee
     rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-meego
 fi
 
-
 %end
 
 %post --nochroot
@@ -64,3 +61,7 @@ if [ -n "$IMG_NAME" ]; then
     echo "BUILD: $IMG_NAME" >> $INSTALL_ROOT/etc/meego-release
 fi
 %end
+
+
+
+
